Repository framgia/sph-sun-overflow, pull requests merged in 2023-03, with the labels that each got.

#138 [Overflow-270] Create Seeder for Teams
  backend/app/Models/Team.php
  backend/database/factories/MemberFactory.php
  backend/database/factories/TeamFactory.php
  backend/database/migrations/2023_03_01_114957_add_slug_to_teams.php
  backend/database/seeders/MemberSeeder.php
  backend/database/seeders/TeamSeeder.php
  backend/database/seeders/UserRelationSeeder.php
  backend/database/seeders/UserSeeder.php
  backend/graphql/team/type.graphql
Labels: Approved by Jules ✅, Approved by Gift ✅

#140 [OVERFLOW-182] [BE] Create API for Update content
  backend/app/GraphQL/Mutations/UpdateTeamDashboard.php
  backend/app/GraphQL/Mutations/UpdateUser.php
  backend/app/Models/Team.php
  backend/graphql/team/mutation.graphql
Labels: Approved by Amber ✅, Approved by Ian ✅

#142 [Overflow-269] [BE] API for teams list
  backend/graphql/team/query.graphql
Labels: Approved by Gift ✅, Approved by Amber ✅

#135 [BUGFIX] Text description of comment event fix
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/Comment/index.tsx
  frontend/pages/questions/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#134 [BUGFIX] Toast when Authentication error on login
  frontend/components/templates/RouteWrapper.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/login/check.tsx
  frontend/pages/login/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#141 [Overflow-64] Teams List Page Markup
  frontend/components/molecules/TeamMembersSidebar/index.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/team/[teamId].tsx
  frontend/pages/teams/[teamId].tsx
  frontend/pages/teams/index.tsx
Labels: For QA Review 🎭, Approved by Jules ✅, Approved by Gift ✅, Kent is Reviewing 🔬

#144 [Overflow-148] Create API for retrieving members
  backend/app/GraphQL/Queries/TeamMembers.php
  backend/graphql/team/query.graphql
Labels: For Code Review 🖥️, Approved by Amber ✅, Due Today 🌇

#145 [OVERFLOW-130, OVERFLOW-65] Create Team Detail Page AND Dashboard component
  frontend/pages/teams/[slug].tsx
  frontend/pages/teams/[teamId].tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Amber ✅

#146 [Overflow-277] Question Form Privacy Markup
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/pages/questions/add.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Gift ✅

#147 [OVERFLOW-70] [FE] Implement Teams API to page
  backend/app/Models/Team.php
  backend/database/factories/MemberFactory.php
  backend/database/factories/TeamFactory.php
  backend/database/seeders/TeamSeeder.php
  backend/graphql/team/type.graphql
  frontend/helpers/graphql/queries/get_teams.ts
  frontend/pages/teams/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Amber ✅, Approved by Ian ✅

#148 [Overflow-291] Update Team Detail API
  backend/app/GraphQL/Queries/Team.php
  backend/app/Models/Team.php
  backend/graphql/team/query.graphql
Labels: Approved by Jules ✅, Approved by Keno ✅

#143 [Overflow-275] Update Question Detail API
  backend/app/GraphQL/Queries/Question.php
Labels: Approved by Keno ✅, Approved by Jhon ✅

#152 [Overflow-142] [FE] Integrate Team Detail Page
  frontend/helpers/graphql/queries/get_team.ts
  frontend/pages/teams/[slug].tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Gift ✅

#154 [OVERFLOW-272] [BE] Update API for Question list
  backend/app/GraphQL/Queries/Questions.php
  backend/app/Models/Team.php
  backend/graphql/question/query.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Amber ✅

#149 [Overflow-288][BUGFIX] UI Modifications
  frontend/components/molecules/Avatar/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/molecules/Votes/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
Labels: Approved by Gift ✅, Approved by Ian ✅

#151 [Overflow-67] [MARKUP] Create Page for Manage Members
  frontend/components/atoms/Icons/index.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/teams/[slug]/manage.tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#153 [Overflow-181] Create page for updating dashboard content
  frontend/components/atoms/Button/index.tsx
  frontend/components/organisms/DashboardEditContentForm/index.tsx
  frontend/pages/teams/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Amber ✅

#155 [Overflow-66] [Markup] Teams Question Tab
  frontend/components/organisms/BookmarkList/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/templates/QuestionPageLayout.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/teams/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#158 [Overflow-71] [FE] Implement Team Questions API to page
  frontend/components/molecules/DropdownFilters/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/templates/QuestionPageLayout.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/questions/tagged/[slug].tsx
  frontend/pages/teams/[slug]/index.tsx
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#156 [Overflow-69] Update add question API to include view settings
  backend/app/GraphQL/Mutations/CreateQuestion.php
  backend/app/GraphQL/Mutations/UpdateQuestion.php
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Zion ✅

#160 [Overflow-147] View Manage Team Implementation
  backend/app/GraphQL/Queries/TeamMembers.php
  backend/app/Models/Team.php
  backend/graphql/team/type.graphql
  frontend/components/molecules/TeamMembersSidebar/index.tsx
  frontend/helpers/graphql/queries/get_members.ts
  frontend/pages/teams/[slug]/manage.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Kent ✅

#165 [Overflow-278] [BE] Update Questions API
  backend/app/GraphQL/Mutations/CreateQuestion.php
  backend/app/GraphQL/Mutations/UpdateQuestion.php
  backend/app/GraphQL/Queries/Questions.php
  backend/app/GraphQL/Queries/TeamMembers.php
  backend/app/Models/Team.php
  backend/graphql/question/query.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Keno ✅, Due Today 🌇

#157 [Overflow-282] [MARKUP] Create Modal Form for Managing Team Members
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/Dropdown/index.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/components/templates/Modal.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/teams/[slug]/manage.tsx
Labels: Approved by Jhon ✅, Approved by Gift ✅, Approved by Kent ✅

#168 [Overflow-183] [FE] Integrate API for team dashboard form and team dashboard component
  backend/database/migrations/2023_01_26_040851_create_teams_table.php
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/organisms/DashboardEditContentForm/index.tsx
  frontend/helpers/graphql/mutations/update_team_dashboard.ts
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/teams/index.tsx
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#161 [Overflow-274] Create Page for Team question detail
  frontend/components/molecules/Pill/index.tsx
  frontend/components/molecules/Tags/index.tsx
  frontend/components/molecules/Tooltip/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/templates/QuestionPageLayout.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/teams/[slug]/question/[question_slug].tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#169 [OVERFLOW-279] [OVERFLOW-280] [FE] Implement updated API to Add Question Form and Questions List Page
  backend/app/GraphQL/Mutations/CreateQuestion.php
  frontend/components/atoms/Icons/index.tsx
  frontend/components/atoms/ProfileImage/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/organisms/ProfileInfo/edit.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/templates/QuestionPageLayout.tsx
  frontend/components/templates/RouteWrapper.tsx
  frontend/helpers/graphql/mutations/create_question.ts
  frontend/helpers/graphql/mutations/update_question.ts
  frontend/helpers/graphql/queries/get_authenticated_user.ts
  frontend/helpers/graphql/queries/get_question.ts
  frontend/helpers/graphql/queries/get_question_skeleton.ts
  frontend/helpers/graphql/queries/get_questions.ts
  frontend/helpers/store.tsx
  frontend/pages/questions/[slug]/edit.tsx
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/teams/[slug]/manage.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#167 [Overflow-287] [Bugfix] Add Show All Filter
  backend/app/Console/Kernel.php
  backend/app/Exceptions/CustomException.php
  backend/app/Http/Middleware/RedirectIfAuthenticated.php
  backend/app/Models/GraphQLPassportSocialite/HasSocialLogin.php
  frontend/components/molecules/DropdownFilters/index.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Kent ✅

#172 [Overflow-301] [BE] Get team roles API
  backend/graphql/team/query.graphql
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Gift ✅

#171 [OVERFLOW-300] Create API to get users that are not yet members of the team
  backend/app/GraphQL/Mutations/CreateQuestion.php
  backend/app/GraphQL/Queries/AllUsers.php
  backend/graphql/user/query.graphql
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Amber ✅

#174 [Overflow-302] [BUGFIX] Create Deleting confirmation modal
  frontend/components/organisms/Table/index.tsx
Labels: Approved by Keno ✅, Approved by Gift ✅, Approved by Amber ✅

#173 [Overflow-281] [FE] Implement Roles list API and Users List API to the Form modal
  backend/app/GraphQL/Queries/AllUsers.php
  frontend/helpers/graphql/queries/get_all_users.ts
  frontend/helpers/graphql/queries/get_members.ts
  frontend/helpers/graphql/queries/get_team_roles.ts
  frontend/pages/teams/[slug]/manage.tsx
Labels: Approved by Keno ✅, Approved by Gift ✅, Approved by Amber ✅

#175 [Oveflow-271][FE] Implement team API to component
  frontend/components/molecules/TeamMembersSidebar/index.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/queries/sidebar.ts
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#178 [Overflow-286] [FE] Implement add, edit, remove api to Modals
  frontend/components/molecules/Dropdown/index.tsx
  frontend/components/organisms/EditMember/index.tsx
  frontend/components/organisms/ManageMembersActions/index.tsx
  frontend/components/organisms/RemoveMember/index.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/components/templates/Modal.tsx
  frontend/helpers/graphql/mutations/add_member.ts
  frontend/helpers/graphql/mutations/delete_member.ts
  frontend/helpers/graphql/mutations/update_member.ts
  frontend/pages/teams/[slug]/manage.tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#177 [OVERFLOW-306] BugFix - Fix bugs in Teams List Page and Team Detail Page
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/helpers/graphql/queries/get_user.ts
  frontend/helpers/store.tsx
  frontend/pages/questions/add.tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/index.tsx
  frontend/pages/users/[slug].tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#176 [Overflow-303] [BUGFIX] Fix bugs in Questions
  frontend/components/molecules/Author/index.tsx
  frontend/components/molecules/Avatar/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/AnswerForm/index.tsx
  frontend/components/organisms/Comment/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/templates/QuestionPageLayout.tsx
  frontend/helpers/graphql/queries/get_question.ts
  frontend/helpers/graphql/queries/get_questions.ts
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#179 [Overflow-304] [Bugfix] Fix Bugs in Tags List and Tag Detail Page
  frontend/components/molecules/Pill/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/molecules/Tooltip/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/templates/QuestionsPageLayout.tsx
  frontend/components/templates/RouteWrapper.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/queries/get_authenticated_user.ts
  frontend/helpers/graphql/queries/sidebar.ts
  frontend/helpers/store.tsx
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/questions/tagged/[slug].tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/teams/[slug]/manage.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/index.tsx
  frontend/pages/teams/index.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#180 [OVERFLOW-305] Fix bugs in the User Profile and User Dropdown
  backend/app/GraphQL/Queries/AllUsers.php
  backend/app/Observers/AnswerObserver.php
  backend/app/Observers/CommentObserver.php
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/AnswerBookmark/index.tsx
  frontend/helpers/graphql/queries/get_bookmarks.ts
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#181 [OVERFLOW-111] - Create API for deleting team
  backend/app/GraphQL/Mutations/DeleteTeam.php
  backend/graphql/team/mutation.graphql
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#185 [OVERFLOW-348] Implement sub menus for manage (admin stuff) in left sidebar
  frontend/components/atoms/SidebarIcon/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/pages/manage/tags.tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#182 [Overflow-327] [MARKUP] Create Page for Team Detail (Admin)
  frontend/components/atoms/PageStats/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
Labels: Approved by Gift ✅, Approved by Ian ✅, Approved by Kent ✅

#183 [OVERFLOW-90] Create API for assigning a role to a user
  backend/app/GraphQL/Mutations/AssignRole.php
  backend/graphql/user/mutation.graphql
Labels: For Code Review 🖥️, Approved by Keno ✅, Approved by Amber ✅

#189 [Overflow-328] [FE] Implement Get Team API to Team Detail Page (Admin)
  backend/app/Models/Team.php
  backend/graphql/team/type.graphql
  frontend/helpers/graphql/queries/get_team.ts
  frontend/pages/manage/teams/[slug]/index.tsx
Labels: Approved by Jhon ✅, Approved by Gift ✅, Approved by Ian ✅

#184 [Overflow-104] [Markup] Create a page for teams (Admin)
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/Tooltip/index.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/manage/teams/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Amber ✅, Due Today 🌇, Gift is Reviewing 🔬

#186 [Overflow-73] [MARKUP] Create a page for Roles
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/PermissionPill/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/organisms/DeleteRole/index.tsx
  frontend/components/organisms/EditRole/index.tsx
  frontend/components/organisms/PermissionPills/index.tsx
  frontend/components/organisms/RoleForm/index.tsx
  frontend/components/organisms/RolesAction/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/manage/roles/index.tsx
Labels: For Code Review 🖥️, Approved by Keno ✅, Approved by Amber ✅, Due Today 🌇

#191 [Overflow-76] [BE] Create API for storing roles with permissions
  backend/app/GraphQL/Directives/HasPermissionsDirective.php
  backend/app/GraphQL/Mutations/CreateRole.php
  backend/graphql/role/mutation.graphql
Labels: For Code Review 🖥️, Approved by Keno ✅, Approved by Gift ✅, Approved by Ian ✅, Due Today 🌇

#192 [OVERFLOW-349] [BE] Create API for retrieving teams of user
  backend/app/GraphQL/Queries/UserTeams.php
  backend/app/Observers/AnswerObserver.php
  backend/app/Observers/CommentObserver.php
  backend/app/Observers/TeamObserver.php
  backend/app/Providers/EventServiceProvider.php
  backend/graphql/member/type.graphql
  backend/graphql/team/mutation.graphql
  backend/graphql/user/query.graphql
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Ian ✅

#188 [OVERFLOW-91] [BE] Create API for retrieving user with its questions and answers
  backend/app/GraphQL/Queries/Answers.php
  backend/app/GraphQL/Queries/Questions.php
  backend/graphql/answer/query.graphql
  backend/graphql/question/query.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Amber ✅

#195 [Overflow-74] [MARKUP] Implement deletion modals
  frontend/.eslintrc.json
  frontend/components/organisms/DeleteRole/index.tsx
  frontend/pages/manage/roles/index.tsx
Labels: For QA Review 🎭, Approved by Keno ✅, Approved by Gift ✅, Approved by Amber ✅

#194 [Overflow-82] [FE] Implement API to page
  backend/graphql/role/query.graphql
  backend/graphql/role/type.graphql
  frontend/.eslintrc.js
  frontend/.eslintrc.json
  frontend/components/molecules/PermissionPill/index.tsx
  frontend/components/organisms/PermissionPills/index.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/helpers/graphql/queries/get_roles.ts
  frontend/helpers/graphql/queries/get_roles_paginate.ts
  frontend/pages/manage/roles/index.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#198 [OVERFLOW-102][FE] Implement tags list paginated APIs to page
  frontend/pages/manage/tags/index.tsx
Labels: For QA Review 🎭, Approved by Amber ✅, Approved by Ian ✅, Due Today 🌇, Gift is Reviewing 🔬

#193 [Overflow-112] [FE] Implement API to admin teams page
  frontend/components/molecules/CustomComboBox/index.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/manage/teams/index.tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#199 [Overflow-81] [BE] Create API for deleting roles with its permissions
  backend/app/GraphQL/Mutations/DeleteRole.php
  backend/graphql/role/mutation.graphql
Labels: For Code Review 🖥️, Approved by Gift ✅, Approved by Ian ✅, Due Today 🌇

#202 [Overflow-101] [BE] Create API for deleting tags
  backend/app/GraphQL/Mutations/DeleteTag.php
  backend/database/seeders/PermissionSeeder.php
  backend/graphql/tag/mutation.graphql
Labels: Approved by Keno ✅, Approved by Gift ✅, Due Today 🌇

#200 [Overflow-86] [MARKUP] Create page for viewing of user (Admin)
  frontend/components/templates/layouts/index.tsx
  frontend/pages/manage/users/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#187 [Overflow-96] [MARKUP] Create form and Implement modal for add/edit tags
  frontend/components/organisms/TagsFormModal/index.tsx
  frontend/pages/test/tagsform.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#205 [OVERFLOW-75] & [OVERFLOW-311] [MARKUP] Create form for Roles & Create page for creating roles
  frontend/components/molecules/Pill/index.tsx
  frontend/components/organisms/RoleForm/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/manage/roles/create.tsx
  frontend/pages/manage/roles/index.tsx
  frontend/tailwind.config.js
Labels: For QA Review 🎭, Approved by Jules ✅, Approved by Amber ✅, Due Today 🌇

#204 [Overflow-84] [MARKUP] Create page for users (Admin)
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/manage/users/index.tsx
Labels: Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#209 [Overflow-97] [Overflow-100] [BE] Create API for storing and updating tags
  backend/app/GraphQL/Mutations/CreateTag.php
  backend/app/GraphQL/Mutations/DeleteTag.php
  backend/app/GraphQL/Mutations/UpdateTag.php
  backend/app/Models/Tag.php
  backend/database/seeders/PermissionSeeder.php
  backend/graphql/tag/mutation.graphql
Labels: For Code Review 🖥️, Approved by Keno ✅, Approved by Ian ✅

#197 [Overflow-347] [MARKUP] Implement Team Members table
  frontend/components/organisms/Table/index.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#210 [Overflow-99] [BE] Create API for retrieving 1 tag
  backend/graphql/tag/query.graphql
Labels: For Code Review 🖥️, Approved by Keno ✅, Approved by Gift ✅

#206 [OVERFLOW-85] - [MARKUP] Create modal for assigning Roles to user
  frontend/components/templates/Modal.tsx
  frontend/pages/manage/users/index.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#207 [Overflow-312] [MARKUP] Create page for updating roles
  frontend/components/organisms/EditRole/index.tsx
  frontend/components/organisms/RoleForm/index.tsx
  frontend/components/organisms/RolesAction/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/queries/get_roles_paginate.ts
  frontend/package-lock.json
  frontend/pages/manage/roles/[slug]/edit.tsx
  frontend/pages/manage/roles/index.tsx
Labels: Approved by Keno ✅, Approved by Gift ✅, Approved by Kent ✅

#212 [Overflow-107] [BE] Create API for storing teams
  backend/app/GraphQL/Mutations/CreateTeam.php
  backend/app/GraphQL/Mutations/DeleteTeam.php
  backend/database/migrations/2023_01_26_040851_create_teams_table.php
  backend/graphql/team/mutation.graphql
Labels: For Code Review 🖥️, Approved by Keno ✅, Approved by Ian ✅

#211 [Overflow-105] [MARKUP] Implement Deletion Modal
  frontend/pages/manage/teams/index.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#216 [OVERFLOW-369] Create API to fetch all team leaders
  backend/app/GraphQL/Queries/TeamLeaders.php
  backend/graphql/user/query.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Amber ✅

#214 [Overflow-106] [MARKUP] Create form and Implement modal for add/edit teams
  backend/app/GraphQL/Queries/Teams.php
  backend/graphql/team/query.graphql
  frontend/components/molecules/Dropdown/index.tsx
  frontend/components/organisms/TagsFormModal/index.tsx
  frontend/components/organisms/TeamsFormModal/index.tsx
  frontend/helpers/graphql/queries/get_teams.ts
  frontend/pages/manage/teams/index.tsx
  frontend/pages/teams/index.tsx
Labels: Approved by Gift ✅, Approved by Ian ✅, Approved by Kent ✅

#215 [OVERFLOW-323] [FE] Implement API to page Tag add/edit
  frontend/components/organisms/Table/index.tsx
  frontend/components/organisms/TagsAction/index.tsx
  frontend/components/organisms/TagsFormModal/index.tsx
  frontend/helpers/graphql/mutations/create_tag.ts
  frontend/helpers/graphql/mutations/update_tag.ts
  frontend/helpers/graphql/queries/get_tag.ts
  frontend/pages/manage/tags/index.tsx
  frontend/pages/test/tagsform.tsx
  frontend/pages/users/index.tsx
Labels: For Rebase 🔀, Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#217 [OVERFLOW-346] Question List
  frontend/components/molecules/DropdownFilters/index.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/teams/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#220 [Overflow-95] [MARKUP] Implement Deletion Modal for Tags
  frontend/components/organisms/TagsAction/index.tsx
Labels: For QA Review 🎭, Approved by Keno ✅, Approved by Ian ✅, Due Today 🌇, Gift is Reviewing 🔬

#218 [Overflow-334] [MARKUP] Implement Delete Modal for Admin Team Members
  frontend/components/atoms/Button/index.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Amber ✅

#219 [OVERFLOW-332] && [OVERFLOW-333] Implement component for questions of the team and implment API
  frontend/pages/manage/teams/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Amber ✅

#222 [Overflow-325] [FE] Implement Delete Tag API to page
  frontend/components/organisms/TagsAction/index.tsx
  frontend/helpers/graphql/mutations/delete_tag.ts
  frontend/pages/manage/tags/index.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Gift ✅

#221 [Overflow-319] [FE] Implement delete team API
  backend/graphql/team/type.graphql
  frontend/helpers/graphql/mutations/delete_team.ts
  frontend/package-lock.json
  frontend/pages/manage/teams/index.tsx
Labels: Approved by Keno ✅, Approved by Gift ✅, Approved by Amber ✅

#224 [Overflow-373] [BUGFIX] Tag Tooltip
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/Pill/index.tsx
  frontend/components/molecules/Tooltip/index.tsx
  frontend/pages/questions/tagged/[slug].tsx
Labels: For QA Review 🎭, Approved by Jules ✅, Approved by Ian ✅, Due Today 🌇

#223 [OVERFLOW-372] [BUGFIX] Truncate data in table tags
  backend/app/Models/Tag.php
  backend/graphql/tag/query.graphql
  backend/graphql/tag/type.graphql
  frontend/components/organisms/Table/index.tsx
  frontend/helpers/graphql/queries/get_tags.ts
  frontend/pages/manage/tags/index.tsx
Labels: For QA Review 🎭, Approved by Jules ✅, Approved by Amber ✅, Due Today 🌇

#225 [OVERFLOW-336,344,337] Implement manage members (add, edit, delete)
  backend/app/GraphQL/Mutations/AddMember.php
  backend/app/GraphQL/Mutations/DeleteMember.php
  backend/app/GraphQL/Mutations/UpdateMember.php
  backend/app/GraphQL/Queries/TeamMembers.php
  frontend/components/organisms/RemoveMember/index.tsx
  frontend/components/templates/MemberManage.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/teams/[slug]/manage.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#227 [Overflow-317] [FE] Implement create and edit team in admin teams page
  backend/app/GraphQL/Mutations/UpdateTeam.php
  backend/app/Models/Team.php
  backend/graphql/tag/query.graphql
  backend/graphql/team/type.graphql
  frontend/components/organisms/TeamsFormModal/index.tsx
  frontend/components/templates/QuestionsPageLayout.tsx
  frontend/helpers/graphql/mutations/create_team.ts
  frontend/helpers/graphql/mutations/update_team.ts
  frontend/helpers/graphql/queries/get_all_team_leaders.ts
  frontend/helpers/graphql/queries/get_team.ts
  frontend/helpers/graphql/queries/get_teams.ts
  frontend/package-lock.json
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/manage/teams/index.tsx
Labels: For QA Review 🎭, Approved by Gift ✅, Approved by Ian ✅, Approved by Kent ✅, Due Today 🌇

#226 [Overflow-92] [FE] Implement API to Admin Users Page List and Details
  frontend/helpers/graphql/mutations/assign_role.ts
  frontend/helpers/graphql/queries/get_role_selection.ts
  frontend/helpers/graphql/queries/get_users_admin.ts
  frontend/pages/manage/users/[slug]/index.tsx
  frontend/pages/manage/users/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#230 [Overlow-380] [Bugfix] My Teams Bugfix
  frontend/components/molecules/TeamSidebar/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Kent ✅

#228 [Overflow-377] [BUGFIX] Fix Edit Tag (Admin)
  frontend/pages/manage/tags/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Kent ✅

#231 [Overflow-379, 383, 378] [BUGFIX] Comment and Answer
  backend/.env.example
  backend/app/GraphQL/Mutations/ToggleFollow.php
  backend/app/GraphQL/Mutations/UpsertVote.php
  backend/app/Observers/AnswerObserver.php
  backend/app/Observers/CommentObserver.php
  backend/app/Observers/UserRelationObserver.php
  backend/app/Observers/VoteObserver.php
Labels: Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#233 [OVERFLOW-385] Team Question Bugs
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/templates/QuestionsPageLayout.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#237 [Overflow-388] [BUGFIX] Change Teams Search Result Message
  frontend/pages/teams/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Kent ✅

#236 [Overflow-381] [Bugfix] Validate if user edited an Answer
  frontend/components/organisms/AnswerForm/index.tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#235 [Overflow-387] [BUGFIX] Show title in bookmark questions and reposition the bookmark icon
  frontend/components/molecules/Bookmark/index.tsx
  frontend/components/organisms/AnswerBookmark/index.tsx
  frontend/components/organisms/BookmarkList/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#239 [OVERFLOW-427] Refractor Navbar
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/SearchBar/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/Navbar/index.tsx
Labels: For QA Review 🎭, Approved by Jules ✅, Approved by Gift ✅, Approved by Amber ✅, Approved by Chevy ✅, Approved by Zion ✅

#238 [Overflow-390] [Overflow-423] [MARKUP] Create 403 and 404 page
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/403.tsx
  frontend/pages/404.tsx
Labels: For Code Review 🖥️, Approved by Gift ✅, Approved by Amber ✅, Due Today 🌇, Approved by Chevy ✅

#240 [Overflow-398] Refactor Users List Page
  frontend/components/atoms/SidebarIcon/index.tsx
  frontend/components/molecules/SearchInput/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/molecules/UserCard/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/users/index.tsx
  frontend/styles/sidebar.css
  frontend/tailwind.config.js
Labels: For QA Review 🎭, Approved by Jules ✅, Approved by Keno ✅, Approved by Gift ✅, Due Today 🌇, Approved by Chevy ✅, Approved by Zion ✅
