Repository framgia/sph-sun-overflow, pull requests merged in 2023-04, with the labels that each got.

#241 [OVERFLOW-405] - Refactor Admin tables
  backend/app/GraphQL/Queries/Teams.php
  backend/app/Models/Team.php
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/PermissionPill/index.tsx
  frontend/components/organisms/EditRole/index.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/components/organisms/TagsAction/index.tsx
  frontend/components/templates/MemberManage.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/manage/roles/index.tsx
  frontend/pages/manage/tags/index.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/manage/teams/index.tsx
  frontend/pages/manage/users/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅, Approved by Chevy ✅

#242 [Overflow-397] Refactor User Tags Page
  frontend/components/molecules/SearchInput/index.tsx
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/tags/index.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅, Approved by Chevy ✅

#243 [Overflow-401] Refactor Team Leader Page
  frontend/components/atoms/BackButton/index.tsx
  frontend/components/molecules/Dropdown/index.tsx
  frontend/components/organisms/EditMember/index.tsx
  frontend/components/organisms/ManageMembersActions/index.tsx
  frontend/components/organisms/RemoveMember/index.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/components/templates/MemberManage.tsx
  frontend/components/templates/Modal.tsx
  frontend/pages/teams/[slug]/manage.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Kent ✅

#244 [Overflow-404] Refactor Admin Tags Page
  backend/graphql/tag/query.graphql
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/organisms/TagsFormModal/index.tsx
  frontend/components/organisms/TeamsFormModal/index.tsx
  frontend/pages/index.tsx
  frontend/pages/manage/tags/index.tsx
  frontend/pages/manage/teams/index.tsx
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#245 [Overflow-396] Refactor Add/Edit Question Page
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/questions/[slug]/edit.tsx
  frontend/pages/questions/add.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/edit.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/index.tsx
  frontend/styles/RichTextEditor.css
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#248 [Overflow-407] [BUGFIX] Most recent and least recent filters in Question List Page
  backend/graphql/question/query.graphql
  frontend/components/molecules/DropdownFilters/index.tsx
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#250 [Overflow-442] [BUGFIX] Disable hover effect on selected menu
  frontend/components/molecules/SidebarButton/index.tsx
Labels: Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#251 [Overflow-448] [BE] Add Category Column to Permissions Migration File
  backend/database/migrations/2023_04_11_080825_add_category_to_permissions_table.php
  backend/database/seeders/PermissionSeeder.php
  backend/graphql/role/type.graphql
Labels: Approved by Jules ✅, Approved by Amber ✅, Due Today 🌇

#249 [Overflow-447] [BUGFIX] Truncate Tag Title in Tags Page Card
  backend/app/GraphQL/Mutations/CreateTag.php
  backend/app/GraphQL/Mutations/UpdateTag.php
  frontend/components/molecules/Pill/index.tsx
  frontend/pages/tags/index.tsx
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#254 [Overflow-445] [BUGFIX] Truncate Profile Name in Profile Dropdown
  backend/app/GraphQL/Mutations/UpdateUser.php
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/ProfileInfo/edit.tsx
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#252 [Overflow-443] [BUGFIX] Auto-hide Admin Submenu
  frontend/components/molecules/SidebarButton/index.tsx
Labels: Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#253 [Overflow-444] [BUGFIX] Change Input in Add Watched Tags
  frontend/components/molecules/CustomComboBox/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/helpers/store.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#255 [Overflow-358] [BE] Create API for retrieving user's questions
  backend/app/GraphQL/Queries/Questions.php
  backend/graphql/question/query.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Jhon ✅, Approved by Ian ✅, Due Today 🌇

#257 [Overflow-360] [BE] Create API for retrieving user's teams
  backend/app/GraphQL/Mutations/UpdateTag.php
  backend/app/GraphQL/Queries/Teams.php
  backend/graphql/team/query.graphql
Labels: Approved by Jules ✅, Approved by Jhon ✅, Approved by Kent ✅, Due Today 🌇

#262 [HOTFIX] Google login hotfix
  frontend/components/templates/RouteWrapper.tsx
  frontend/pages/login/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅

#256 [Overflow-446] [BUGFIX] Watched Tags Modification
  frontend/components/molecules/WatchedTags/index.tsx
Labels: Approved by Jhon ✅, Approved by Amber ✅, Approved by Kent ✅

#247 [OVERFLOW-394] paginator Refractor
  frontend/components/organisms/Paginate/index.tsx
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#264 [Overflow-452] Refactor layout
  frontend/components/templates/layouts/TopLayout.tsx
  frontend/components/templates/layouts/TopLeftLayout.tsx
  frontend/components/templates/layouts/TopLeftRightLayout.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/login/index.tsx
  frontend/tailwind.config.js
Labels: Approved by Amber ✅, Approved by Kent ✅, Approved by Chevy ✅

#258 [Overflow-359] [BE] Create API for getting user's answers
  backend/app/GraphQL/Queries/Answers.php
  backend/graphql/answer/query.graphql
Labels: Approved by Amber ✅, Approved by Ian ✅

#269 [Overflow-355] [Overflow-449] [MARKUP] Create User Detail Page for Admin
  frontend/components/atoms/Icons/Chevron.tsx
  frontend/components/atoms/Icons/Dots.tsx
  frontend/components/atoms/Icons/Eye.tsx
  frontend/components/atoms/Icons/Grid.tsx
  frontend/components/atoms/Icons/List.tsx
  frontend/components/atoms/Icons/Lock.tsx
  frontend/components/atoms/Icons/ThumbUp.tsx
  frontend/components/atoms/Icons/Unlock.tsx
  frontend/components/atoms/Icons/Users.tsx
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/Privacy/index.tsx
  frontend/components/molecules/Tag/index.tsx
  frontend/components/molecules/Tags/index.tsx
  frontend/components/molecules/TeamCard/index.tsx
  frontend/components/molecules/ViewToggle/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionGridItem/index.tsx
  frontend/components/organisms/QuestionListItem/index.tsx
  frontend/components/templates/layouts/TopLayout.tsx
  frontend/components/templates/layouts/TopLeftLayout.tsx
  frontend/components/templates/layouts/TopLeftRightLayout.tsx
  frontend/pages/_document.tsx
  frontend/pages/manage/users/[slug]/index.tsx
  frontend/pages/questions/[slug]/index.tsx
  frontend/tailwind.config.js
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅, Approved by Chevy ✅

#266 [Overflow-403] Refactor Admin Roles Page
  backend/app/GraphQL/Mutations/CreateRole.php
  backend/app/GraphQL/Mutations/UpdateRole.php
  backend/app/Models/Role.php
  backend/graphql/role/query.graphql
  backend/graphql/role/type.graphql
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/Checkbox/index.tsx
  frontend/components/atoms/Icons/index.tsx
  frontend/components/atoms/InputField/index.tsx
  frontend/components/atoms/TextArea/index.tsx
  frontend/components/molecules/PermissionPill/index.tsx
  frontend/components/organisms/DeleteRole/index.tsx
  frontend/components/organisms/EditRole/index.tsx
  frontend/components/organisms/PermissionPills/index.tsx
  frontend/components/organisms/RoleForm/index.tsx
  frontend/components/organisms/RoleFormModal/index.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/components/templates/Modal.tsx
  frontend/helpers/graphql/queries/get_permissions.ts
  frontend/helpers/graphql/queries/get_roles_paginate.ts
  frontend/pages/manage/roles/[slug]/edit.tsx
  frontend/pages/manage/roles/create.tsx
  frontend/pages/manage/roles/index.tsx
  frontend/public/svg/Dot.svg
  frontend/tailwind.config.js
Labels: Approved by Keno ✅, Approved by Ian ✅, Approved by Kent ✅

#259 [Overflow-391] Redirect Users from accessing /manage
  backend/database/seeders/PermissionSeeder.php
  backend/graphql/role/query.graphql
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/components/templates/AdminWrapper.tsx
  frontend/components/templates/RouteWrapper.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/queries/get_authenticated_user.ts
  frontend/helpers/graphql/queries/get_roles.ts
  frontend/helpers/store.tsx
  frontend/pages/403.tsx
  frontend/pages/404.tsx
  frontend/pages/users/[slug].tsx
  frontend/utils/index.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#265 [Overflow-450] Feature/refactor navbar
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/templates/layouts/TopLayout.tsx
  frontend/components/templates/layouts/TopLeftLayout.tsx
  frontend/components/templates/layouts/TopLeftRightLayout.tsx
  frontend/tailwind.config.js
Labels: Approved by Amber ✅, Approved by Ian ✅, Due Today 🌇

#268 [Overflow-451] Refactor left sidebar
  frontend/components/atoms/SidebarIcon/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/components/templates/layouts/TopLeftLayout.tsx
  frontend/components/templates/layouts/TopLeftRightLayout.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/_app.tsx
  frontend/tailwind.config.js
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Ian ✅, Due Today 🌇

#271 [Overflow-460] [Bugfix] Tags Debounce for TagsListPage
  frontend/components/molecules/CustomComboBox/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#273 [Overflow-458][BUGFIX] Question Detail Bugfix
  frontend/components/organisms/AnswerForm/index.tsx
  frontend/components/organisms/CommentForm/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Kent ✅

#267 [Overflow-400] Refactor Profile Page
  backend/app/GraphQL/Mutations/UpdateUser.php
  backend/app/Models/Answer.php
  backend/app/Models/Question.php
  backend/app/Models/User.php
  backend/database/factories/UserFactory.php
  backend/graphql/answer/type.graphql
  backend/graphql/question/type.graphql
  backend/graphql/user/type.graphql
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/TextArea/index.tsx
  frontend/components/molecules/FollowCard/index.tsx
  frontend/components/molecules/ProfileCard/index.tsx
  frontend/components/molecules/SummaryCard/index.tsx
  frontend/components/molecules/Tag/index.tsx
  frontend/components/organisms/AnswerBookmark/index.tsx
  frontend/components/organisms/BookmarkList/index.tsx
  frontend/components/organisms/BookmarkTabContent/index.tsx
  frontend/components/organisms/EditProfileModal/index.tsx
  frontend/components/organisms/EditProfileModal/schema.ts
  frontend/components/organisms/FollowModal/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/organisms/ProfileInfo/edit.tsx
  frontend/components/organisms/ProfileInfo/index.tsx
  frontend/components/templates/Modal.tsx
  frontend/components/templates/Profile.tsx
  frontend/helpers/graphql/mutations/update_user.ts
  frontend/helpers/graphql/queries/get_user.ts
  frontend/helpers/store.tsx
  frontend/pages/users/[slug].tsx
  frontend/styles/globals.css
  frontend/utils/index.tsx
Labels: Approved by Jules ✅, Approved by Kent ✅, Amber is Reviewing 🔬

#282 [HOTFIX] Fix lazy query refetch error
  frontend/pages/users/index.tsx
Labels: Due Today 🌇

#272 [Overflow-455] [Bugfix] Add Question Reloading on Tag Input
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/pages/questions/[slug]/edit.tsx
  frontend/pages/questions/add.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/edit.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#283 [Overflow-470] [Bugfix] Users accessing questions, users, and teams not exist
  frontend/components/templates/Profile.tsx
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/users/[slug].tsx
Labels: Approved by Keno ✅, Approved by Amber ✅

#281 [Overflow-471] [Bugfix] Admin accessing users and teams not exist
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/manage/users/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Amber ✅

#280 [Overflow-478] Refactor Admin Teams Page
  backend/graphql/role/query.graphql
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/InputField/index.tsx
  frontend/components/atoms/TextArea/index.tsx
  frontend/components/molecules/Dropdown/index.tsx
  frontend/components/organisms/EditMember/index.tsx
  frontend/components/organisms/RoleFormModal/index.tsx
  frontend/components/organisms/Table/index.tsx
  frontend/components/organisms/TeamsFormModal/index.tsx
  frontend/components/templates/MemberManage.tsx
  frontend/pages/manage/roles/index.tsx
  frontend/pages/manage/teams/index.tsx
  frontend/pages/manage/users/index.tsx
Labels: For Code Review 🖥️, Approved by Keno ✅, Approved by Ian ✅

#284 [Overflow-479] [Bugfix] TagsInput having 6 tags
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/organisms/QuestionForm/schema.tsx
Labels: For QA Review 🎭, Approved by Amber ✅

#277 [Overflow-426] Refactor Team Detail Page
  backend/app/GraphQL/Queries/TeamMembers.php
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/TabItem/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/molecules/Tabs/index.tsx
  frontend/components/molecules/TeamUserCard/index.tsx
  frontend/components/organisms/DashboardEditContentForm/index.tsx
  frontend/components/organisms/ManageMembersActions/index.tsx
  frontend/components/organisms/ManageMembersTab/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/organisms/RemoveMember/index.tsx
  frontend/components/templates/QuestionsPageLayout.tsx
  frontend/helpers/graphql/queries/get_members.ts
  frontend/helpers/graphql/queries/get_team.ts
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/teams/[slug]/manage.tsx
Labels: For QA Review 🎭, Approved by Jules ✅, Overdue 💥💥💥

#289 [HOTFIX] Answer will display after submitting an answer
  frontend/components/organisms/AnswerForm/index.tsx
Labels: For QA Review 🎭, Approved by Amber ✅, Approved by Ian ✅

#290 [Overflow-488] [Bugfix] Page Refresh on Submit
  frontend/components/organisms/RoleFormModal/index.tsx
  frontend/components/organisms/TagsFormModal/index.tsx
Labels: Approved by Amber ✅, Approved by Kent ✅

#285 [Overflow-458] Refactor Users Page
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/SearchInput/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/molecules/StackedUsers/index.tsx
  frontend/components/molecules/TeamMembersSidebar/index.tsx
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/molecules/UserCard/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/Paginate/index.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/users/[slug].tsx
  frontend/pages/users/index.tsx
Labels: Approved by Keno ✅, Approved by Kent ✅
