Repository framgia/sph-sun-overflow, pull requests merged in 2023-05, with the labels that each got.

#287 [Overflow-481] Refactor User Tags Page
  frontend/components/atoms/Icons/Eye.tsx
  frontend/components/atoms/Icons/Filter.tsx
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/CustomComboBox/index.tsx
  frontend/components/molecules/DropdownFilters/index.tsx
  frontend/components/molecules/FormAlert/index.tsx
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/PermissionPill/index.tsx
  frontend/components/molecules/Pill/index.tsx
  frontend/components/molecules/SearchBar/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/molecules/Tag/index.tsx
  frontend/components/molecules/TagsCard/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/molecules/TeamMembersSidebar/index.tsx
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/templates/Profile.tsx
  frontend/components/templates/QuestionsPageLayout.tsx
  frontend/components/templates/layouts/TopLeftRightLayout.tsx
  frontend/helpers/graphql/queries/get_tags.ts
  frontend/pages/403.tsx
  frontend/pages/404.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/tags/index.tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/styles/globals.css
Labels: Approved by Amber ✅, Approved by Kent ✅

#291 [Overflow-494] [BUGFIX] Question List Scroll and Grid Items
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/organisms/QuestionGridItem/index.tsx
  frontend/pages/_document.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/tags/index.tsx
  frontend/styles/globals.css
Labels: Approved by Amber ✅, Approved by Kent ✅

#286 [Overflow-487] [Bugfix] The new roles are not displayed immediately on the users page when edit a role (Admin)
  backend/app/GraphQL/Mutations/DeleteRole.php
  frontend/pages/manage/users/index.tsx
Labels: Approved by Amber ✅, Approved by Kent ✅

#293 [Overflow-499] Team Members count is duplicated for the Team Leader.
  backend/app/GraphQL/Mutations/CreateTeam.php
  backend/app/Observers/TeamObserver.php
  frontend/components/molecules/TeamUserCard/index.tsx
  frontend/components/organisms/ManageMembersTab/index.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
Labels: Approved by Amber ✅, Approved by Kent ✅

#296 [Overflow-496] [BUGFIX] Duplicate questions change URL
  backend/app/GraphQL/Mutations/DeleteRole.php
  backend/app/GraphQL/Queries/Question.php
  backend/app/Models/Question.php
  backend/graphql/question/query.graphql
  frontend/helpers/graphql/queries/get_question.ts
  frontend/pages/questions/index.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/index.tsx
Labels: Approved by Amber ✅, Approved by Kent ✅

#294 [Overflow-500] [Bugfix] Delete Team Bug
  backend/app/Observers/TeamObserver.php
Labels: Approved by Amber ✅, Approved by Kent ✅

#295 [Overflow-477] Refactor Tags Page
  backend/app/GraphQL/Mutations/CreateTag.php
  frontend/components/organisms/TagsAction/index.tsx
  frontend/components/organisms/TagsFormModal/index.tsx
  frontend/pages/manage/tags/index.tsx
Labels: Approved by Jules ✅, Approved by Kent ✅

#297 [Overflow-506] Cannot Parse all HTML
  frontend/components/molecules/SummaryCard/index.tsx
  frontend/pages/questions/index.tsx
  frontend/utils/index.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅

#298 [HOTFIX] Change Popover minimum height
  frontend/components/molecules/TagPopover/index.tsx
Labels: For Code Review 🖥️, Approved by Jhon ✅

#300 [HOTFIX] Refetch questions after adding watched tags in right sidebar
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/pages/users/index.tsx
Labels: For Code Review 🖥️

#302 [Overflow-498] [Bugfix] Profile Picture does not update
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/EditProfileModal/index.tsx
Labels: For QA Review 🎭, Approved by Jules ✅

#305 [Overflow-504] [Bugfix] Wrong text size and color for Right Sidebar
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅

#304 [Overflow-501] [BUGFIX] Capitalize tag and display humanized created_at
  frontend/components/templates/QuestionsPageLayout.tsx
  frontend/pages/questions/tagged/[slug].tsx
Labels: Approved by Keno ✅, Approved by Ian ✅

#303 [Overflow-508] [BUGFIX] Question Details Page Watch/Unwatched Tags
  frontend/components/molecules/TagPopover/index.tsx
Labels: Approved by Keno ✅, Approved by Ian ✅

#288 [OVERFLOW-482] Refactor Teams Page
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/pages/teams/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅

#301 [OVERFLOW-514] Profile images should be only one per user
  backend/app/GraphQL/Mutations/CreateTeam.php
  backend/app/GraphQL/Mutations/UpdateUser.php
  backend/app/Observers/TeamObserver.php
Labels: Approved by Jules ✅, Approved by Amber ✅

#292 [Overflow-490] Refactor Question Add Page
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/EditorPreview/index.tsx
  frontend/components/molecules/PreviewToggle/index.tsx
  frontend/components/molecules/PublicToggle/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/pages/questions/[slug]/edit.tsx
  frontend/pages/questions/add.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/edit.tsx
  frontend/styles/RichTextEditor.css
Labels: For Code Review 🖥️, Approved by Amber ✅

#306 [Overflow-509] Question Details Page Team Options
  frontend/components/organisms/RoleFormModal/index.tsx
  frontend/pages/manage/roles/index.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/manage/users/[slug]/hooks/useTabData.ts
  frontend/pages/manage/users/index.tsx
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/index.tsx
  frontend/pages/users/[slug].tsx
  frontend/plugins/apollo-client.ts
Labels: For Code Review 🖥️, Approved by Amber ✅

#307 [Overflow-492] [BUGFIX] Table width adjusts on pagination click
  frontend/components/organisms/RoleFormModal/index.tsx
  frontend/components/organisms/TagsFormModal/index.tsx
  frontend/components/organisms/TeamsFormModal/index.tsx
  frontend/pages/manage/roles/index.tsx
  frontend/pages/manage/users/index.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅

#308 [Overflow-495] [MARKUP] Dynamic Table Width
  frontend/components/organisms/Table/index.tsx
  frontend/pages/manage/users/index.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅

#309 [Overflow-502] [BUGFIX] User page filters cannot be reset
  frontend/pages/users/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅

#312 [Overflow-517] [HOTFIX] Manage Users Page Scrollbar
  frontend/pages/manage/users/index.tsx
Labels: For Code Review 🖥️, Approved by Ian ✅, Due Today 🌇

#310 [Overflow-503] [Overflow-493] Manage Team UI Improvements
  frontend/components/atoms/PageStats/index.tsx
  frontend/components/atoms/TabItem/index.tsx
  frontend/components/templates/QuestionsPageLayout.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/teams/[slug]/index.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Jules is Reviewing 🔬

#311 [Overflow-497] Manage Incorrect Error
  frontend/components/organisms/TeamsFormModal/index.tsx
  frontend/pages/manage/teams/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅

#313 [OVERFLOW-513] Create pre-commit linter
  .gitignore
  .php-cs-fixer.php
  .pre-commit-config.yaml
  README.md
Labels: Approved by Jules ✅, Approved by Amber ✅

#314 [Overflow-511] Update Code Review PR Template
  pull-request-template.md
Labels: For Code Review 🖥️, Approved by Amber ✅

#315 [Overflow-516][BUGFIX] Manage Tags Page
  frontend/pages/manage/tags/index.tsx
Labels: Approved by Jules ✅, Approved by Keno ✅

#316 [Overflow-461] [BUGFIX] Handle modal button states
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/Icons/Loading.tsx
  frontend/components/atoms/Icons/index.tsx
  frontend/components/organisms/RoleFormModal/index.tsx
  frontend/components/organisms/TagsAction/index.tsx
  frontend/components/organisms/TagsFormModal/index.tsx
  frontend/components/organisms/TeamsFormModal/index.tsx
  frontend/components/templates/Modal.tsx
  frontend/pages/manage/roles/index.tsx
  frontend/pages/manage/teams/index.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅

#320 [Overflow-516] [BUGFIX] Manage Tags Page
  frontend/components/organisms/Table/index.tsx
  frontend/pages/manage/tags/index.tsx
Labels: For Code Review 🖥️, Approved by Ian ✅, Due Today 🌇

#323 [Overflow-522] [BUGFIX] Change text color in Tag Details Page
  frontend/components/templates/QuestionsPageLayout.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Approved by Ian ✅, Due Today 🌇

#321 [Overflow-519] [BUGFIX] Update HTML Page Title for Pages
  frontend/components/atoms/PageTitle/index.tsx
  frontend/components/organisms/RoleFormModal/index.tsx
  frontend/components/organisms/TagsFormModal/index.tsx
  frontend/components/organisms/TeamsFormModal/index.tsx
  frontend/pages/403.tsx
  frontend/pages/404.tsx
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/index.tsx
  frontend/pages/manage/roles/index.tsx
  frontend/pages/manage/tags/index.tsx
  frontend/pages/manage/teams/index.tsx
  frontend/pages/manage/users/index.tsx
  frontend/pages/questions/[slug]/edit.tsx
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/questions/add.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/questions/tagged/[slug].tsx
  frontend/pages/tags/index.tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/teams/index.tsx
  frontend/pages/users/[slug].tsx
  frontend/pages/users/index.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Approved by Ian ✅, Due Today 🌇

#322 [OVERFLOW-520] Bugfix Manage Teams Page fix min height problem
  frontend/components/organisms/Table/index.tsx
  frontend/pages/manage/roles/index.tsx
  frontend/pages/manage/tags/index.tsx
  frontend/pages/manage/teams/index.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Jules is Reviewing 🔬

#319 [Overflow-515] [Bugfix] Question Form
  frontend/components/molecules/EditorPreview/index.tsx
  frontend/components/molecules/PreviewToggle/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/pages/questions/[slug]/edit.tsx
  frontend/pages/questions/add.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/edit.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Due Today 🌇

#317 [Overflow-518][BUGFIX] Users Page Filter Results
  frontend/pages/users/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Due Today 🌇

#324 [Overflow-523] [BUGFIX] Team Detail Page
  backend/app/Observers/TeamObserver.php
  frontend/components/molecules/TeamUserCard/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Due Today 🌇

#325 [Overflow-524] [BUGFIX] Update Title for Pages
  frontend/components/atoms/PageTitle/index.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅

#327 [OVERFLOW-467] Create login page for admin login
  frontend/pages/admin/login.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Due Today 🌇

#326 [Overflow-525] [BUGFIX] Teams Page Scrollbar
  frontend/pages/teams/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Due Today 🌇

#328 [Overflow-526] Update active button design
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/ProfileCard/index.tsx
  frontend/components/molecules/TagsCard/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Due Today 🌇

#330 [OVERFLOW-468.OVERFLOW-469] Create API and implement in admin login page
  backend/app/GraphQL/Mutations/AdminLogin.php
  backend/app/Models/Question.php
  backend/database/factories/UserFactory.php
  backend/database/migrations/2023_05_10_141252_add_password_to_users.php
  backend/database/seeders/DatabaseSeeder.php
  backend/graphql/schema.graphql
  frontend/components/atoms/InputField/index.tsx
  frontend/helpers/graphql/mutations/admin_login.ts
  frontend/pages/admin/login.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Due Today 🌇, Jules is Reviewing 🔬

#329 [Overflow-464] [BUGFIX] Display a loading spinner for async requests
  frontend/pages/manage/roles/index.tsx
  frontend/pages/manage/tags/index.tsx
  frontend/pages/manage/teams/index.tsx
  frontend/pages/manage/users/index.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/questions/tagged/[slug].tsx
  frontend/pages/tags/index.tsx
  frontend/pages/teams/index.tsx
  frontend/pages/users/index.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Due Today 🌇

#331 [Overflow-474] [Bugfix] [Share, Close, Delete] buttons in Question Detail Page
  backend/app/GraphQL/Mutations/DeleteAnswer.php
  backend/app/GraphQL/Mutations/DeleteComment.php
  backend/app/GraphQL/Mutations/DeleteQuestion.php
  backend/app/Models/Answer.php
  backend/app/Models/Question.php
  backend/graphql/answer/mutation.graphql
  backend/graphql/comment/mutation.graphql
  backend/graphql/question/mutation.graphql
  frontend/components/atoms/ClickAction/index.tsx
  frontend/components/atoms/Icons/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/AnswerList/index.tsx
  frontend/components/organisms/Comment/index.tsx
  frontend/components/organisms/DeleteAnswer/index.tsx
  frontend/components/organisms/DeleteComment/index.tsx
  frontend/components/organisms/DeleteQuestion/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/templates/ContentCard.tsx
  frontend/helpers/copyLink.tsx
  frontend/helpers/graphql/mutations/delete_answer.ts
  frontend/helpers/graphql/mutations/delete_comment.ts
  frontend/helpers/graphql/mutations/delete_question.ts
Labels: Approved by Keno ✅, Approved by Amber ✅, Amber is Reviewing 🔬

#335 [OVERFLOW-530] Table UI bugs
  frontend/components/organisms/Table/index.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Due Today 🌇

#336 [Overflow-521] [Bugfix] RTE Image Upload
  backend/app/Console/Commands/DeleteTempImages.php
  backend/app/Console/Kernel.php
  backend/app/GraphQL/Mutations/CreateQuestion.php
  backend/app/GraphQL/Mutations/UpdateQuestion.php
  backend/app/GraphQL/Mutations/UploadImage.php
  backend/app/Helpers/MoveImages.php
  backend/graphql/question/mutation.graphql
  frontend/components/molecules/EditorPreview/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/helpers/graphql/mutations/upload_image.ts
  frontend/helpers/reactQuill/imagePreview.ts
Labels: Approved by Keno ✅, Approved by Amber ✅

#337 [Overflow-527] [FE] Implement admin update password
  frontend/components/atoms/Icons/ChangePass.tsx
  frontend/components/atoms/Icons/index.tsx
  frontend/components/atoms/InputField/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/organisms/UpdatePasswordModal/index.tsx
  frontend/components/templates/RouteWrapper.tsx
  frontend/helpers/graphql/mutations/update_password.ts
  frontend/helpers/graphql/queries/get_authenticated_user.ts
  frontend/helpers/store.tsx
  frontend/pages/admin/login.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅

#338 [Overflow-532] [BUGFIX] Question Detail text spacing adjustments
  frontend/components/organisms/QuestionDetail/index.tsx
Labels: For Code Review 🖥️, Approved by Ian ✅

#339 [Overflow-536] [Bugfix] Card Header Overflow
  frontend/components/molecules/TagsCard/index.tsx
  frontend/components/molecules/TeamCard/index.tsx
  frontend/components/templates/ContentCard.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅

#340 [Overflow-535] [BUGFIX] Same border color to filters
  frontend/components/molecules/SortDropdown/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅

#341 [Overflow-538] [BUGFIX] Tags Input dropdown margin
  frontend/components/molecules/TagsInput/index.tsx
Labels: Approved by Keno ✅, Approved by Amber ✅

#342 [OVERFLOW-539] Incorrect size and color in "No teams to show"
  frontend/components/organisms/Table/index.tsx
  frontend/pages/manage/teams/[slug]/index.tsx
  frontend/pages/manage/users/[slug]/index.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/tags/index.tsx
  frontend/pages/teams/[slug]/index.tsx
  frontend/pages/teams/index.tsx
  frontend/pages/users/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅

#343 [Overflow-534] [Bugfix] Change Break All to Word Break
  frontend/components/molecules/SummaryCard/index.tsx
  frontend/components/molecules/TagsCard/index.tsx
  frontend/components/molecules/TeamCard/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/Comment/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionListItem/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅

#344 [Overflow-533] There's a shadow for the heading 'My Teams'
  frontend/components/molecules/CustomComboBox/index.tsx
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
Labels: Approved by Amber ✅, Approved by Ian ✅

#347 [Overflow-544] [BUGFIX] Teams dropdown in Add Question form
  frontend/components/molecules/SortDropdown/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅, Due Today 🌇

#346 [Overflow-540] [BUGFIX] Input fields are not aligned fix
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Due Today 🌇

#345 [Overflow-542] [BUGFIX] Change password modal fixes
  frontend/components/atoms/InputField/index.tsx
  frontend/components/atoms/TextArea/index.tsx
  frontend/components/molecules/Dropdown/index.tsx
  frontend/components/organisms/RoleFormModal/index.tsx
  frontend/components/organisms/TeamsFormModal/index.tsx
  frontend/components/organisms/UpdatePasswordModal/index.tsx
  frontend/styles/globals.css
Labels: For Code Review 🖥️, Approved by Amber ✅, Approved by Ian ✅, Due Today 🌇

#348 [Overflow-537] [Bugfix] Questions Details Page change the close/back button design
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/ClickBack/index.tsx
  frontend/components/organisms/DeleteQuestion/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/teams/[slug]/question/[question-slug]/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅, Due Today 🌇

#350 [Overflow-545] RTE Image Paste Not Embedded
  frontend/components/molecules/EditorPreview/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/helpers/reactQuill/customClipboard.ts
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Amber ✅

#351 [Overflow-546] [Bugfix] Right Side bar
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Amber ✅, Due Today 🌇

#352 [Overflow-531] Refactor Login Page
  frontend/components/atoms/Button/index.tsx
  frontend/components/organisms/LoginCard/index.tsx
  frontend/pages/admin/login.tsx
  frontend/pages/login/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅

#353 [Overflow-543] [BUGFIX] Fix overflow text in Question Card
  frontend/styles/globals.css
Labels: Approved by Amber ✅, Approved by Ian ✅

#349 [Overflow-547] [BUGFIX] Image display in List View and Grid View
  frontend/components/organisms/QuestionGridItem/index.tsx
  frontend/components/organisms/QuestionListItem/index.tsx
  frontend/helpers/htmlParsing.tsx
  frontend/pages/questions/index.tsx
  frontend/styles/globals.css
Labels: Approved by Keno ✅, Approved by Amber ✅

#355 [OVERFLOW-541] Admin Login Page eye icon show only when password has value
  frontend/components/organisms/UpdatePasswordModal/index.tsx
  frontend/pages/admin/login.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅

#356 [Overflow-549] [BUGFIX] Grid View application error
  frontend/helpers/htmlParsing.tsx
Labels: Approved by Amber ✅, Approved by Ian ✅

#358 [Overflow-550] [BUGFIX] Team Details card size
  frontend/pages/teams/[slug]/index.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Approved by Ian ✅, Due Today 🌇

#357 [Overflow-548] [Bugfix] Manage User Profile
  frontend/components/organisms/QuestionListItem/index.tsx
  frontend/pages/manage/users/[slug]/index.tsx
Labels: For Code Review 🖥️, Approved by Amber ✅, Jules is Reviewing 🔬

#359 [Overflow-551] [BUGFIX] Login Card border overflow
  frontend/components/organisms/LoginCard/index.tsx
Labels: Approved by Jhon ✅, Approved by Amber ✅

#360 [Overflow-553] [Bugfix] Change "Select Role" to "Select Designation"
  frontend/components/organisms/ManageMembersTab/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
Labels: For Code Review 🖥️, Approved by Keno ✅

#361 [Overflow-544] [Bugfix] Change Filters Icon
  frontend/pages/tags/index.tsx
  frontend/pages/users/index.tsx
Labels: Approved by Keno ✅

#362 [Overflow-555] [Bugfix] Question Details Page Truncate
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/Comment/index.tsx
Labels: Approved by Keno ✅

#364 [Overflow-557] [Bugfix] Follow/Following Modal in Manage Users
  frontend/pages/manage/users/[slug]/hooks/useTabData.ts
  frontend/pages/manage/users/[slug]/index.tsx
Labels: For Code Review 🖥️

#365 [Overflow-556] [Bugfix] Dashboard Empty Message
  frontend/components/organisms/DashboardEditContentForm/index.tsx
  frontend/pages/teams/[slug]/index.tsx
Labels: Approved by Keno ✅
