Repository framgia/sph-sun-overflow, pull requests merged in 2023-02, with the labels that each got.

#40 [Overflow-12] Get api for my teams
  backend/graphql/schema.graphql
  backend/graphql/team/query.graphql
  backend/graphql/team/type.graphql
  backend/graphql/user/type.graphql
Labels: Approved by Jhon ✅, Approved by Ian ✅

#34 [Overflow-21] Create API for retrieving Question, Answers, and Comments
  backend/composer.lock
  backend/graphql/answer/type.graphql
  backend/graphql/question/query.graphql
Labels: For Rebase 🔀, Approved by Gift ✅, For Today 🌇

#42 [Overflow-186] Retrieve Question List API
  backend/app/GraphQL/Queries/Questions.php
  backend/config/lighthouse.php
  backend/graphql/question/query.graphql
  backend/graphql/question/type.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅, For Today 🌇

#35 [OVERFLOW-177] Implement RouteProtection in Next
  backend/.gitignore
  backend/app/GraphQL/Mutations/SocialLogin.php
  backend/app/Models/GraphQLPassportSocialite/HasSocialLogin.php
  backend/app/Models/User.php
  backend/graphql/auth.graphql
  frontend/.gitignore
  frontend/components/atoms/Loader/ThreeCirclesSpinner.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/templates/RouteWrapper.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/mutations/social_login.ts
  frontend/helpers/graphql/queries/get_authenticated_user.ts
  frontend/helpers/graphql/users/Mutations.tsx
  frontend/helpers/graphql/users/Queries.tsx
  frontend/helpers/loaderSpinnerHelper.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/login/check.tsx
  frontend/pages/login/index.tsx
  frontend/styles/globals.css
Labels: Approved by Jules ✅, Approved by Amber ✅

#39 [Overflow-26] - [Bugfix] - Create Api for adding answers
  backend/app/GraphQL/Mutations/CreateAnswer.php
  backend/graphql/answer/mutation.graphql
Labels: Approved by Keno ✅, Approved by Amber ✅

#31 [Overflow-20] Implement Question Component
  backend/graphql/question/mutation.graphql
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/Avatar/index.tsx
  frontend/components/molecules/Bookmark/index.tsx
  frontend/components/molecules/Pill/index.tsx
  frontend/components/molecules/Tags/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/molecules/Votes/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/Sidebar/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/package-lock.json
  frontend/pages/questions/[id].tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Kent ✅

#48 [Overflow-219] Add .prettierrc config file
  frontend/.prettierrc
Labels: For Code Review 🖥️, Approved by Amber ✅, Approved by Ian ✅, For Today 🌇

#44 [Overflow-37] Create API for Posting Question
  backend/app/Exceptions/CustomException.php
  backend/app/GraphQL/Mutations/CreateQuestion.php
  backend/app/Models/Question.php
  backend/app/Models/Tag.php
  backend/database/migrations/2023_02_02_095142_add_team_id_to_questions_table.php
  backend/database/migrations/2023_02_03_014656_create_question_tag_table.php
  backend/database/migrations/2023_02_03_014919_create_question_tag_table.php
  backend/graphql/question/mutation.graphql
  backend/graphql/question/type.graphql
Labels: Approved by Keno ✅, Approved by Gift ✅, For Today 🌇

#46 [Overflow-27] Create and Update Comments
  backend/app/GraphQL/Mutations/CreateComment.php
  backend/app/GraphQL/Mutations/UpdateComment.php
  backend/graphql/comment/mutation.graphql
  backend/graphql/question/query.graphql
Labels: Approved by Jules ✅, Approved by Keno ✅

#47 [Overflow-32] [BE] Create API for Accepting Answer
  backend/app/GraphQL/Mutations/AcceptAnswer.php
  backend/graphql/answer/mutation.graphql
Labels: For Code Review 🖥️, Approved by Gift ✅, Keno is Reviewing 🔬

#51 [Overflow-37] [Bugfix] Create API for Posting Question
  backend/app/GraphQL/Mutations/CreateQuestion.php
  backend/graphql/question/mutation.graphql
Labels: For Code Review 🖥️, For Today 🌇

#52 [Overflow-223] Bugfix Create API for retrieving Question only
  backend/app/Models/Question.php
  backend/database/seeders/VoteSeeder.php
  backend/graphql/question/type.graphql
Labels: For Code Review 🖥️, For Today 🌇

#54 [Overflow-219] [BUGFIX] Run format script to follow Prettier
  frontend/.eslintrc.json
  frontend/.prettierignore
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/Icons/index.tsx
  frontend/components/atoms/Loader/ThreeCirclesSpinner.tsx
  frontend/components/atoms/SidebarIcon/index.tsx
  frontend/components/atoms/Tag/index.tsx
  frontend/components/molecules/Avatar/index.tsx
  frontend/components/molecules/Bookmark/index.tsx
  frontend/components/molecules/FormAlert/index.tsx
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/Pill/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/molecules/SearchBar/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/molecules/Tags/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/molecules/Votes/index.tsx
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/components/organisms/QuestionForm/schema.tsx
  frontend/components/templates/ProvidersWrapper.tsx
  frontend/components/templates/RouteWrapper.tsx
  frontend/helpers/graphql/mutations/social_login.ts
  frontend/helpers/graphql/queries/get_authenticated_user.ts
  frontend/helpers/graphql/users/Mutations.tsx
  frontend/helpers/graphql/users/Queries.tsx
  frontend/helpers/loaderSpinnerHelper.tsx
  frontend/helpers/localStorageHelper.ts
  frontend/next.config.js
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/api/auth/[...nextauth].ts
  frontend/pages/api/hello.ts
  frontend/pages/index.tsx
  frontend/pages/login/check.tsx
  frontend/pages/login/index.tsx
  frontend/plugins/apollo-client.ts
  frontend/postcss.config.js
  frontend/styles/globals.css
  frontend/styles/login.css
  frontend/tsconfig.json
  frontend/utils/index.tsx
Labels: For Code Review 🖥️, Approved by Gift ✅, Approved by Amber ✅, For Today 🌇

#49 [Overflow-220] Get API for Tag Suggestions
  backend/graphql/tag/query.graphql
Labels: Approved by Jules ✅, Approved by Amber ✅

#50 [Overflow-221] Add/Remove Api for WatchedTags
  backend/app/GraphQL/Mutations/AddWatchedTag.php
  backend/app/GraphQL/Mutations/RemoveWatchedTag.php
  backend/graphql/user/mutation.graphql
Labels: Approved by Jules ✅, Approved by Amber ✅

#36 [Overflow-23] Question Page - Answer Component
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/AcceptAnswer/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/package-lock.json
  frontend/pages/questions/[id].tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Kent ✅

#58 [Overflow-27] [BUGFIX] Create and Update Comments API
  backend/app/GraphQL/Mutations/CreateComment.php
  backend/graphql/answer/mutation.graphql
  backend/graphql/comment/mutation.graphql
Labels: Approved by Jules ✅, Approved by Jhon ✅

#45 [Overflow-117] [FE] Integrate api for answer form and component
  backend/app/GraphQL/Mutations/CreateAnswer.php
  backend/graphql/answer/mutation.graphql
  backend/graphql/answer/query.graphql
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/templates/RouteWrapper.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/mutations/create_answer.tsx
  frontend/helpers/store.tsx
  frontend/helpers/toast.tsx
  frontend/package.json
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#56 [OVERFLOW-201] Integration of Question Detail API to page
  backend/app/Models/Question.php
  backend/app/Models/Tag.php
  backend/graphql/question/type.graphql
  backend/graphql/tag/type.graphql
  frontend/components/molecules/Avatar/index.tsx
  frontend/components/molecules/Tags/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/helpers/graphql/queries/get_question.ts
  frontend/pages/questions/[id].tsx
Labels: Approved by Gift ✅, Approved by Ian ✅, Approved by Kent ✅, For Today 🌇

#59 [OVERFLOW-225] Update migration, model for Question && [OVERFLOW-226] Update API for get question for views count and slug
  backend/app/GraphQL/Queries/Question.php
  backend/app/Models/Question.php
  backend/database/migrations/2023_02_06_065010_add_slug_and_views_count_to_questions.php
  backend/graphql/question/query.graphql
  backend/graphql/question/type.graphql
Labels: For Rebase 🔀, Approved by Gift ✅, Approved by Amber ✅

#63 [OVERFLOW-227] [FE] Implement API to Question detail Page
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/helpers/graphql/queries/get_question.ts
  frontend/helpers/htmlParsing.tsx
  frontend/package.json
  frontend/pages/questions/[slug].tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Kent ✅

#66 [OVERFLOW-229] Create Model , Migration, and Seeder for Bookmarks
  backend/app/Models/Answer.php
  backend/app/Models/Bookmark.php
  backend/app/Models/Question.php
  backend/app/Models/User.php
  backend/database/factories/BookmarkFactory.php
  backend/database/migrations/2023_02_07_074707_create_bookmarks_table.php
  backend/database/seeders/BookmarkSeeder.php
  backend/database/seeders/DatabaseSeeder.php
Labels: For Code Review 🖥️, Approved by Amber ✅, Approved by Ian ✅, For Today 🌇

#62 [OVERFLOW-22] Implement Comments Form Component
  frontend/components/CommentForm/index.tsx
  frontend/components/CommentForm/schema.tsx
  frontend/components/atoms/Button/index.tsx
  frontend/pages/questions/[slug].tsx
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#64 [Overflow-38] Integrate API for question form page
  frontend/components/molecules/Avatar/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/molecules/Tags/index.tsx
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/components/organisms/QuestionForm/schema.tsx
  frontend/components/organisms/Sidebar/index.tsx
  frontend/components/templates/RouteWrapper.tsx
  frontend/helpers/graphql/mutations/create_answer.ts
  frontend/helpers/graphql/mutations/create_question.ts
  frontend/helpers/graphql/queries/get_question.ts
  frontend/helpers/store.tsx
  frontend/helpers/toast.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/questions/[slug].tsx
  frontend/pages/questions/add.tsx
Labels: Approved by Jhon ✅, Approved by Amber ✅, Approved by Kent ✅

#68 [OVERFLOW-22] Fix edit if from user and commenform directory
  backend/app/Models/Question.php
  backend/graphql/question/type.graphql
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/organisms/CommentForm/index.tsx
  frontend/components/organisms/CommentForm/schema.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/helpers/graphql/queries/get_question.ts
  frontend/helpers/htmlParsing.tsx
  frontend/package-lock.json
  frontend/pages/questions/[slug].tsx
Labels: Approved by Jules ✅, Approved by Amber ✅

#55 [Overflow-14] Implement API to Sidebars
  backend/app/GraphQL/Mutations/AddWatchedTag.php
  backend/graphql/schema.graphql
  frontend/components/molecules/CustomComboBox/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/molecules/StackedUsers/index.tsx
  frontend/components/molecules/TeamMembersSidebar/index.tsx
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/components/organisms/Sidebar/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/mutations/sidebar.ts
  frontend/helpers/graphql/queries/sidebar.ts
  frontend/package-lock.json
  frontend/pages/profile.tsx
  frontend/pages/questions.tsx
  frontend/pages/team/[teamId].tsx
  frontend/pages/teams.tsx
  frontend/utils/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅, Due Today 🌇

#65 [Overflow-115] [FE] Implement the get comments api in Question Page
  backend/config/app.php
  frontend/components/organisms/Comment/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/helpers/graphql/queries/get_question.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/questions/[slug].tsx
  frontend/tsconfig.json
Labels: For QA Review 🎭, Approved by Keno ✅, Approved by Gift ✅, Due Today 🌇, Gift is Reviewing 🔬

#67 [Overflow-204] Display the Answers Component Dynamically
  backend/app/Models/Answer.php
  backend/app/Models/User.php
  backend/graphql/answer/type.graphql
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/Comment/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/queries/get_question.ts
  frontend/package-lock.json
  frontend/pages/questions/[slug].tsx
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Gift ✅, Due Today 🌇

#69 [BUGFIX] Bugfix implement api in answer
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/components/organisms/Comment/index.tsx
  frontend/helpers/toast.tsx
  frontend/package-lock.json
  frontend/pages/questions/[slug].tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅

#73 [Overflow-30] [Bugfix] Create API for Voting
  backend/app/GraphQL/Mutations/UpsertVote.php
  backend/app/Models/Answer.php
  backend/app/Models/Question.php
  backend/graphql/answer/type.graphql
  backend/graphql/question/type.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Due Today 🌇, Keno is Reviewing 🔬

#72 [Overflow-31] Create API for bookmark
  backend/app/GraphQL/Mutations/ToggleBookmark.php
  backend/composer.lock
  backend/graphql/bookmark/mutation.graphql
  backend/graphql/bookmark/type.graphql
  backend/graphql/schema.graphql
  frontend/package-lock.json
  frontend/plugins/apollo-client.ts
Labels: For Code Review 🖥️, Approved by Amber ✅, Due Today 🌇, Keno is Reviewing 🔬

#61 [Overflow-185] Create Question list page
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/Author/index.tsx
  frontend/components/molecules/Filters/index.tsx
  frontend/components/organisms/Paginate/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/package-lock.json
  frontend/pages/questions.tsx
  frontend/pages/questions/[slug].tsx
  frontend/pages/questions/index.tsx
  frontend/tailwind.config.js
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#70 [Overflow-230] [FE] Implement the get comments api for Answers
  backend/app/Models/Answer.php
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/helpers/graphql/queries/get_question.ts
  frontend/package-lock.json
  frontend/pages/questions/[slug].tsx
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#75 [Overflow-129] [FE] Implement API to check answer component
  backend/app/Models/Question.php
  backend/graphql/question/type.graphql
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/AcceptAnswer/index.tsx
  frontend/components/molecules/CustomComboBox/index.tsx
  frontend/components/molecules/StackedUsers/index.tsx
  frontend/components/molecules/TeamMembersSidebar/index.tsx
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/helpers/graphql/mutations/accept_answer.ts
  frontend/helpers/graphql/queries/get_question.ts
  frontend/helpers/toast.tsx
  frontend/pages/questions/[slug].tsx
  frontend/styles/globals.css
Labels: Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#76 [Overflow-127] [FE] Implement API to Bookmark Component
  backend/app/GraphQL/Mutations/ToggleBookmark.php
  backend/app/Models/Answer.php
  backend/app/Models/Question.php
  backend/graphql/answer/type.graphql
  backend/graphql/question/type.graphql
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/Bookmark/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/helpers/graphql/mutations/toggle_bookmark.ts
  frontend/helpers/graphql/queries/get_question.ts
  frontend/pages/questions/[slug].tsx
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Kent ✅

#79 [Overflow-125] [FE] Implement API to voting component
  backend/app/GraphQL/Queries/Question.php
  backend/app/Models/Answer.php
  backend/graphql/answer/type.graphql
  backend/graphql/question/query.graphql
  frontend/components/atoms/Icons/index.tsx
  frontend/components/molecules/Votes/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/helpers/graphql/mutations/upsert_vote.ts
  frontend/helpers/graphql/queries/get_question.ts
  frontend/helpers/store.tsx
  frontend/pages/questions/[slug].tsx
Labels: Approved by Gift ✅, Approved by Ian ✅, Approved by Kent ✅

#71 [Overflow-7] Apply API to Navbar
  backend/app/Models/UserNotification.php
  backend/database/migrations/2019_11_19_000000_update_social_provider_users_table.php
  backend/graphql/notification/mutation.graphql
  backend/graphql/notification/query.graphql
  backend/graphql/notification/type.graphql
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/SearchBar/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/helpers/graphql/mutations/update_notification.ts
  frontend/helpers/graphql/queries/get_notifications.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/tailwind.config.js
Labels: Approved by Jules ✅, Approved by Keno ✅, Approved by Jhon ✅, Approved by Kent ✅

#80 [Overflow-119] Integrate API to comment form and component
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/AcceptAnswer/index.tsx
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/Comment/index.tsx
  frontend/components/organisms/CommentForm/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/helpers/graphql/mutations/create_comment.ts
  frontend/helpers/graphql/mutations/update_comment.ts
  frontend/pages/questions/[slug].tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#81 [Overflow-187] [FE] Implement API to the question list page including pagination
  backend/graphql/question/query.graphql
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/Filters/index.tsx
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/Paginate/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/helpers/graphql/queries/get_notifications.ts
  frontend/helpers/graphql/queries/get_questions.ts
  frontend/pages/questions/[slug].tsx
  frontend/pages/questions/index.tsx
Labels: Approved by Gift ✅, Approved by Ian ✅, Approved by Kent ✅

#84 [Overflow-234] Bugfix overall component adjustments
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/Filters/index.tsx
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/molecules/TeamMembersSidebar/index.tsx
  frontend/components/molecules/TeamSidebar/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/organisms/Paginate/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/login/index.tsx
  frontend/pages/questions/[slug].tsx
  frontend/pages/questions/add.tsx
  frontend/pages/questions/index.tsx
Labels: For Code Review 🖥️, Approved by Gift ✅, Due Today 🌇

#87 [Overflow-242] [BUGFIX] Bookmark Fix
  frontend/components/molecules/Bookmark/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/QuestionDetail/index.tsx
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Keno ✅

#91 [Overflow-246] [Bugfix] [FE] Redesign filter buttons
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/SortDropdown/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/pages/questions/[slug].tsx
  frontend/pages/questions/index.tsx
Labels: For Code Review 🖥️, Approved by Keno ✅, Approved by Gift ✅

#88 [Overflow-61] Create API for retrieving bookmark
  backend/app/GraphQL/Queries/Bookmarks.php
  backend/graphql/bookmark/query.graphql
Labels: Approved by Keno ✅, Approved by Amber ✅

#93 [Overflow-238] [BE] Update Migration for User
  backend/app/Models/User.php
  backend/database/factories/UserFactory.php
  backend/database/migrations/2023_02_15_132618_add_slug_and_about_me_to_users.php
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Keno ✅

#94 [Overflow-244] [Bugfix] Change Avatar to Initials if No Image
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/package.json
Labels: Approved by Jules ✅, Approved by Amber ✅

#95 [Overflow-40] Create page for tags list
  frontend/components/atoms/Icons/index.tsx
  frontend/components/atoms/PageHeader/index.tsx
  frontend/components/atoms/Tag/index.tsx
  frontend/components/molecules/DropdownFilters/index.tsx
  frontend/components/molecules/Pill/index.tsx
  frontend/components/molecules/SearchBar/index.tsx
  frontend/components/molecules/SearchInput/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/templates/Card.tsx
  frontend/pages/tags/index.tsx
  frontend/styles/globals.css
  frontend/tailwind.config.js
Labels: Approved by Jules ✅, Approved by Amber ✅

#96 [Overflow-45] [BE] Create api for retrieving questions with tag
  backend/app/GraphQL/Queries/Questions.php
  backend/app/Models/User.php
  backend/database/factories/UserFactory.php
  backend/graphql/question/query.graphql
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/queries/get_questions.ts
  frontend/pages/questions/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅

#97 [Overflow-59] [Overflow-60] [BE] Retrieve User API
  backend/app/GraphQL/Mutations/AcceptAnswer.php
  backend/app/GraphQL/Mutations/UpsertVote.php
  backend/app/Models/User.php
  backend/graphql/user/type.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅

#89 [Overflow-53] [MARKUP] Create page for user profile
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/ProfileImage/index.tsx
  frontend/components/atoms/ProfileStats/index.tsx
  frontend/components/molecules/AboutMe/index.tsx
  frontend/components/molecules/WatchedTags/index.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/pages/profile.tsx
  frontend/pages/users/[id].tsx
Labels: For QA Review 🎭, Approved by Jhon ✅, Approved by Gift ✅

#101 [OVERFLOW-17] Create API for question search (sort and query filters)
  backend/app/GraphQL/Queries/Questions.php
  backend/graphql/question/query.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅

#98 [Overflow-41] Create API for retrieving tags (search and filter)
  backend/app/GraphQL/Queries/Tags.php
  backend/app/Models/Tag.php
  backend/graphql/tag/query.graphql
  backend/graphql/tag/type.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Keno ✅

#104 [OVERFLOW-57] Create update profile api
  backend/app/GraphQL/Mutations/UpdateUser.php
  backend/graphql/user/mutation.graphql
Labels: For Code Review 🖥️, Approved by Gift ✅, Approved by Amber ✅

#100 [OVERFLOW-16] Create a page for Search Results
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/SearchBar/index.tsx
  frontend/pages/questions/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Kent ✅

#102 [Overflow-236] [BE] Migration and model for UserRelation
  backend/app/Models/User.php
  backend/app/Models/UserRelation.php
  backend/database/factories/UserRelationFactory.php
  backend/database/migrations/2023_02_16_162500_create_user_relations_table.php
  backend/database/seeders/UserRelationSeeder.php
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Keno ✅

#105 [Overflow-132] [FE] Implement API to profile info component in the page
  backend/app/GraphQL/Queries/User.php
  backend/app/Models/User.php
  backend/graphql/user/query.graphql
  frontend/components/atoms/ProfileImage/index.tsx
  frontend/components/atoms/ProfileStats/index.tsx
  frontend/components/molecules/AboutMe/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/templates/RouteWrapper.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/queries/get_authenticated_user.ts
  frontend/helpers/graphql/queries/get_user.ts
  frontend/helpers/store.tsx
  frontend/package-lock.json
  frontend/pages/users/[id].tsx
  frontend/pages/users/[slug].tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#99 [Overflow-179] [Overflow-44] [Markup] Create page for questions with tag
  backend/app/Models/Tag.php
  backend/database/migrations/2023_02_16_150133_add_slug_to_tags.php
  backend/database/seeders/TagSeeder.php
  backend/graphql/tag/type.graphql
  frontend/components/molecules/DropdownFilters/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/pages/questions/tagged/[slug].tsx
Labels: Approved by Keno ✅, Approved by Ian ✅, Approved by Kent ✅

#111 [Overflow-54] [MARKUP] Implement activity component
  frontend/components/molecules/Activity/index.tsx
  frontend/pages/users/[slug].tsx
Labels: Approved by Amber ✅, Approved by Ian ✅, Approved by Kent ✅

#108 [Overflow-18] [FE] Integrate API to search form and search page
  backend/app/GraphQL/Queries/Questions.php
  backend/app/Models/User.php
  frontend/components/molecules/DropdownFilters/index.tsx
  frontend/components/molecules/SearchBar/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/Sidebar/LeftSideBar.tsx
  frontend/helpers/graphql/queries/get_questions.ts
  frontend/pages/questions/index.tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#112 [Overflow-253] [MARKUP] Edit Question Form Markup
  frontend/components/organisms/QuestionDetail/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/questions/[slug]/edit.tsx
  frontend/pages/questions/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Ian ✅, Approved by Kent ✅

#106 [Overflow-240] [BE] Update Notification API to include Follows
  backend/app/Models/UserRelation.php
  backend/app/Observers/UserRelationObserver.php
  backend/app/Providers/EventServiceProvider.php
  backend/graphql/notification/type.graphql
  backend/graphql/relation/type.graphql
  backend/graphql/schema.graphql
Labels: Approved by Keno ✅, Approved by Ian ✅

#110 [Overflow-241] [FE] Integrate Follows to Notification
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/helpers/graphql/queries/get_notifications.ts
  frontend/package-lock.json
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Kent ✅

#117 [OVERFLOW-257] [BE] Create Update answer API
  backend/app/GraphQL/Mutations/UpdateAnswer.php
  backend/app/GraphQL/Queries/Users.php
  backend/app/Models/GraphQLPassportSocialite/HasSocialLogin.php
  backend/graphql/answer/mutation.graphql
Labels: Approved by Gift ✅, Approved by Amber ✅

#103 [Overflow-48] [MARKUP] Create page for user list w/ components
  backend/graphql/answer/mutation.graphql
  frontend/components/molecules/SearchInput/index.tsx
  frontend/components/molecules/TeamMembersSidebar/index.tsx
  frontend/components/molecules/UserTab/index.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/pages/users/index.tsx
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#119 [Overflow-61][BUGFIX] Create API for retrieving bookmark
  backend/app/GraphQL/Queries/Bookmarks.php
  backend/graphql/bookmark/query.graphql
Labels: Approved by Jhon ✅

#107 [Overflow-237] feature/create-tooltip
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/Pill/index.tsx
  frontend/components/molecules/Tooltip/index.tsx
  frontend/package.json
  frontend/pages/users/[slug].tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#118 [OVERFLOW-252] Create update question API
  backend/app/GraphQL/Mutations/UpdateQuestion.php
  backend/app/Models/Question.php
  backend/graphql/question/mutation.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅

#121 [Overflow-134] Implement API to bookmarks component
  frontend/components/molecules/Author/index.tsx
  frontend/components/organisms/AnswerBookmark/index.tsx
  frontend/components/organisms/AnswerDetail/index.tsx
  frontend/components/organisms/BookmarkList/index.tsx
  frontend/components/organisms/BookmarkTabContent/index.tsx
  frontend/helpers/graphql/queries/get_bookmarks.ts
  frontend/helpers/graphql/queries/get_questions.ts
  frontend/package-lock.json
  frontend/pages/questions/index.tsx
  frontend/pages/users/[slug].tsx
Labels: Approved by Keno ✅, Approved by Amber ✅, Approved by Kent ✅

#126 [OVERFLOW-266] Update question detail API to add sorting of votes and created_at
  backend/app/GraphQL/Queries/Question.php
  backend/app/Models/Question.php
  backend/graphql/question/query.graphql
  backend/graphql/question/type.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Amber ✅

#127 [Overflow-46] [FE] Implement API to filter form and question with tag page
  backend/app/GraphQL/Queries/Questions.php
  backend/graphql/question/query.graphql
  backend/graphql/tag/query.graphql
  frontend/components/molecules/Author/index.tsx
  frontend/components/molecules/DropdownFilters/index.tsx
  frontend/components/molecules/SearchInput/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
  frontend/helpers/graphql/queries/get_questions.ts
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/questions/index.tsx
  frontend/pages/questions/tagged/[slug].tsx
  frontend/pages/tags/index.tsx
Labels: Approved by Keno ✅, Approved by Gift ✅

#129 [Overflow-267] [FE] Integrate sort answers in question detail page
  frontend/helpers/graphql/queries/get_question.ts
  frontend/pages/questions/[slug]/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅

#125 [Overflow-254] Implement update question API to Edit Question Page
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/organisms/AnswerForm/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/helpers/graphql/mutations/update_question.ts
  frontend/helpers/graphql/queries/get_question_skeleton.ts
  frontend/pages/questions/[slug]/edit.tsx
  frontend/pages/questions/[slug]/index.tsx
  frontend/utils/index.tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Amber ✅

#124 [Overflow-58] [BE] Create follows api in profiles
  backend/app/GraphQL/Mutations/ToggleFollow.php
  backend/graphql/relation/mutation.graphql
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅, Due Today 🌇

#128 [Overflow-133] Implement API to activity component
  frontend/components/molecules/Activity/index.tsx
  frontend/components/organisms/AnswerBookmark/index.tsx
  frontend/components/organisms/Sidebar/RightSideBar.tsx
  frontend/helpers/graphql/queries/get_bookmarks.ts
  frontend/helpers/graphql/queries/get_user.ts
  frontend/pages/questions/[slug]/index.tsx
  frontend/pages/users/[slug].tsx
  frontend/styles/globals.css
Labels: Approved by Jules ✅, Approved by Gift ✅

#131 [Overflow-170] [FE] Integrate API for follows
  backend/app/GraphQL/Mutations/ToggleFollow.php
  backend/app/Models/User.php
  backend/app/Observers/UserRelationObserver.php
  backend/graphql/user/type.graphql
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/mutations/toggle_follow.ts
  frontend/helpers/graphql/queries/get_user.ts
  frontend/pages/users/[slug].tsx
Labels: Approved by Jules ✅, Approved by Gift ✅, Approved by Amber ✅

#132 [Overflow-56] Implement profiles edit forms components
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/Icons/index.tsx
  frontend/components/atoms/ProfileImage/index.tsx
  frontend/components/atoms/ProfileStats/index.tsx
  frontend/components/molecules/AboutMe/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/organisms/Paginate/index.tsx
  frontend/components/organisms/ProfileInfo/edit.tsx
  frontend/components/organisms/ProfileInfo/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/users/[slug].tsx
  frontend/styles/profile.css
Labels: Approved by Jules ✅, Approved by Amber ✅, Approved by Kent ✅

#133 [Overflow-249] [FE] Implement toggle Bookmark API
  frontend/components/molecules/Bookmark/index.tsx
  frontend/components/organisms/AnswerBookmark/index.tsx
  frontend/components/organisms/BookmarkList/index.tsx
  frontend/components/organisms/QuestionList/index.tsx
Labels: Approved by Gift ✅, Approved by Amber ✅, Approved by Kent ✅

#137 [OVERFLOW-138] Feature/implement api update profile page
  backend/app/GraphQL/Mutations/UpdateUser.php
  backend/app/Models/User.php
  backend/graphql/user/mutation.graphql
  frontend/components/atoms/ProfileImage/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/organisms/ProfileInfo/edit.tsx
  frontend/components/organisms/ProfileInfo/index.tsx
  frontend/helpers/graphql/mutations/update_user.ts
  frontend/helpers/graphql/queries/get_authenticated_user.ts
  frontend/helpers/graphql/queries/get_notifications.ts
  frontend/helpers/graphql/queries/get_user.ts
  frontend/helpers/store.tsx
  frontend/pages/users/[slug].tsx
Labels: For Code Review 🖥️, Approved by Ian ✅, Due Today 🌇
