Repository framgia/sph-sun-overflow, pull requests merged in 2023-01, with the labels that each got.

#8 [Overflow-155] - [BUG-FIX] Docker BE installing package
  README.md
  backend/Dockerfile
  docker-compose.yml
Labels: approved

#7 [Overflow-161] Setup GraphQL
  backend/app/Models/User.php
  backend/composer.json
  backend/composer.lock
  backend/database/seeders/DatabaseSeeder.php
  backend/graphql/schema.graphql
  backend/graphql/user/mutation.graphql
  backend/graphql/user/query.graphql
  backend/graphql/user/type.graphql
Labels: For Code Review

#13 [Overflow-173] Setup tailwind
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/index.tsx
  frontend/postcss.config.js
  frontend/styles/Home.module.css
  frontend/styles/globals.css
  frontend/tailwind.config.js
Labels: For Code Review

#9 [Overflow-164] - Create migration and seeder files for Roles [BE]
  backend/app/Models/Role.php
  backend/database/migrations/2023_01_19_070828_create_roles_table.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/seeders/RoleSeeder.php
Labels: Approved by Jhon, Approved by Ian

#11 [Overflow-13] Sidebar Markup
  frontend/components/atoms/SidebarIcon/index.tsx
  frontend/components/molecules/SidebarButton/index.tsx
  frontend/components/organisms/Sidebar/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
Labels: Approved by Jhon, Approved by Gift

#10 [Overflow-25] Answer Component
  frontend/components/atoms/Button/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
Labels: Approved by Keno, Approved by Amber

#6 [Overflow-5] Navbar Markup
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/SearchBar/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/public/favicon.ico
  frontend/public/next.svg
  frontend/public/thirteen.svg
  frontend/public/vercel.svg
  frontend/tailwind.config.js
Labels: For Code Review, Approved by Jules, Approved by Ian

#12 [Overflow-165] Create migration and seeder files for Permission [BE]
  backend/app/Models/Permission.php
  backend/database/migrations/2023_01_20_050611_create_permissions_table.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/seeders/PermissionSeeder.php
Labels: For Code Review, Approved by Jhon, Approved by Ian

#16 [Overflow-166] Model, Migration and Seeder Files for Users
  backend/app/Models/Role.php
  backend/app/Models/User.php
  backend/database/factories/UserFactory.php
  backend/database/migrations/2023_01_20_000000_create_users_table.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/seeders/UserSeeder.php
  frontend/.gitignore
  frontend/package-lock.json
Labels: For Code Review, Approved by Jules, Ian is Reviewing

#19 [SUN_OVERFLOW-2] Create form page for login
  frontend/components/atoms/Button/index.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/pages/_app.tsx
  frontend/pages/login.tsx
  frontend/public/images/overflow_logo.png
  frontend/public/images/sun_logo.png
  frontend/styles/login.css
Labels: For QA Review, Approved by Jules, Approved by Amber

#14 [Overflow-174] Set-up color theme
  frontend/pages/index.tsx
  frontend/tailwind.config.js
Labels: For Code Review 🖥️, Approved by Keno ✅, Gift is Reviewing 🔬

#17 [Overflow-167] Model, Migration and Seeder files for Questions
  backend/app/Models/Question.php
  backend/app/Models/User.php
  backend/config/database.php
  backend/database/factories/QuestionFactory.php
  backend/database/migrations/2023_01_20_000000_create_users_table.php
  backend/database/migrations/2023_01_23_014012_create_questions_table.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/seeders/QuestionSeeder.php
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅

#18 [Overflow-172] Pivot table for Roles and Permissions
  backend/app/Models/Permission.php
  backend/app/Models/Role.php
  backend/database/migrations/2023_01_23_032551_permission_role.php
  backend/database/seeders/PermissionSeeder.php
Labels: For Code Review 🖥️, Approved by Jhon ✅, Approved by Ian ✅

#22 [Overflow-5] - [BUGFIX] Update navbar markup
  frontend/components/molecules/NotificationDropdown/index.tsx
  frontend/components/molecules/SearchBar/index.tsx
  frontend/components/molecules/UserDropdown/index.tsx
  frontend/components/organisms/Navbar/index.tsx
  frontend/package-lock.json
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅

#24 [Overflow-26] Create API adding answers
  backend/graphql/answer/mutation.graphql
  backend/graphql/answer/query.graphql
  backend/graphql/answer/type.graphql
  backend/graphql/schema.graphql
Labels: Approved by Keno ✅, Approved by Amber ✅

#26 [Overflow-169] Model, Migration and Seeder Files for Comments
  backend/app/Models/Answer.php
  backend/app/Models/Comment.php
  backend/app/Models/Question.php
  backend/database/factories/CommentFactory.php
  backend/database/migrations/2023_01_24_064358_create_comments_table.php
  backend/database/seeders/CommentSeeder.php
  backend/database/seeders/DatabaseSeeder.php
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅

#28 [Overflow-28] Create API for updating answers
  backend/graphql/answer/mutation.graphql
Labels: Approved by Keno ✅, Approved by Amber ✅

#29 [Overflow-171] Model, Migration and Seeder Files for Votes
  backend/app/Models/Answer.php
  backend/app/Models/Question.php
  backend/app/Models/Vote.php
  backend/database/factories/VoteFactory.php
  backend/database/migrations/2023_01_25_033431_create_votes_table.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/seeders/VoteSeeder.php
Labels: For Code Review 🖥️, Approved by Jules ✅, Approved by Ian ✅

#20 [Overflow-35] Create Question Form
  frontend/components/atoms/Tag/index.tsx
  frontend/components/molecules/FormAlert/index.tsx
  frontend/components/molecules/RichTextEditor/index.tsx
  frontend/components/molecules/TagsInput/index.tsx
  frontend/components/organisms/AnswerComponent/index.tsx
  frontend/components/organisms/QuestionForm/index.tsx
  frontend/components/organisms/QuestionForm/schema.tsx
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/tailwind.config.js
  frontend/utils/index.tsx
Labels: For Code Review 🖥️, Approved by Jhon ✅, Approved by Gift ✅

#23 [Overflow-10] API Get Permissions of User
  backend/graphql/role/query.graphql
  backend/graphql/role/type.graphql
  backend/graphql/schema.graphql
  backend/graphql/user/type.graphql
Labels: Approved by Jhon ✅, Approved by Ian ✅, For Today 🌇

#32 [SUN_OVERFLOW-3] Implement Google authentication to page
  backend/app/Models/User.php
  backend/app/Providers/AuthServiceProvider.php
  backend/composer.json
  backend/config/auth.php
  backend/config/cors.php
  backend/config/lighthouse-graphql-passport.php
  backend/config/services.php
  backend/database/migrations/2019_11_19_000000_update_social_provider_users_table.php
  backend/graphql/auth.graphql
  backend/graphql/schema.graphql
  backend/graphql/user/mutation.graphql
  backend/graphql/user/query.graphql
  frontend/.env
  frontend/components/templates/ProvidersWrapper.tsx
  frontend/components/templates/layouts/index.tsx
  frontend/helpers/graphql/Mutations.tsx
  frontend/helpers/graphql/Queries.tsx
  frontend/helpers/localStorageHelper.ts
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/api/auth/[...nextauth].ts
  frontend/pages/login.tsx
  frontend/plugins/apollo-client.ts
Labels: Approved by Jules ✅, Approved by Amber ✅

#27 [Overflow-175] Create migration and seeder files for Tags
  backend/app/Models/Tag.php
  backend/app/Models/User.php
  backend/database/migrations/2023_01_25_031917_create_tags_table.php
  backend/database/migrations/2023_01_26_055630_tag_user.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/seeders/TagSeeder.php
Labels: For Code Review 🖥️, Approved by Jhon ✅, Approved by Ian ✅, For Today 🌇

#30 [Overflow-11] Get API for watched tags
  backend/app/Models/Tag.php
  backend/app/Models/User.php
  backend/graphql/schema.graphql
  backend/graphql/tag/query.graphql
  backend/graphql/tag/type.graphql
  backend/graphql/user/type.graphql
Labels: For Code Review 🖥️, Approved by Jhon ✅, Approved by Ian ✅, For Today 🌇

#33 [Overflow-176] Create migration and seeder files for Teams, Team Role…
  backend/app/Models/Member.php
  backend/app/Models/Team.php
  backend/app/Models/TeamRole.php
  backend/app/Models/User.php
  backend/composer.lock
  backend/database/migrations/2019_11_17_000000_create_roles_table.php
  backend/database/migrations/2019_11_18_000000_create_users_table.php
  backend/database/migrations/2023_01_26_040851_create_teams_table.php
  backend/database/migrations/2023_01_26_041049_create_team_roles_table.php
  backend/database/migrations/2023_01_27_020638_create_members_table.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/seeders/MemberSeeder.php
  backend/database/seeders/TeamRoleSeeder.php
  backend/database/seeders/TeamSeeder.php
Labels: For Code Review 🖥️, Approved by Ian ✅, For Today 🌇
